export const KOREAN_CARD_MAP = {
  // 마술사 핵심 덱 메인 몬스터 및 싱크로/엑시즈/링크
  '천룡의 마술사': 'Dragonpit Magician',
  '조현의 마술사': 'Harmonizing Magician',
  '자독의 마술사': 'Purple Poison Magician',
  '혜안의 마술사': 'Wisdom-Eye Magician',
  '홍채의 마술사': 'Double Iris Magician',
  '백익의 마술사': 'White Wing Magician',
  '흑아의 마술사': 'Black Fang Magician',
  '홍귀의 마술사': 'Oafdragon Magician',
  '각검의 마술사': 'Oafdragon Magician',
  '용혈의 마술사': 'Dragonpit Magician',
  '용맥의 마술사': 'Dragonpulse Magician',
  '아스트로그래프 마술사': 'Astrograph Sorcerer',
  '아스트로그래프 매지션': 'Astrograph Sorcerer',
  '아스트로그래프': 'Astrograph Sorcerer',
  '크로노그래프 마술사': 'Chronograph Sorcerer',
  '크로노그래프 매지션': 'Chronograph Sorcerer',
  '별을 읽는 마술사': 'Stargazer Magician',
  '시간을 읽는 마술사': 'Timegazer Magician',
  '귀룡의 마술사': 'Nobledragon Magician',
  '법안의 마술사': 'Dharma-Eye Magician',
  '조율의 마술사': 'Tuning Magician',
  '천공의 마술사': 'Performapal Celestial Magician',
  'EM 천공의 마술사': 'Performapal Celestial Magician',
  'EM 도크로배트 조커': 'Performapal Skullcrobat Joker',
  '도크로배트 조커': 'Performapal Skullcrobat Joker',
  '도크로배트': 'Performapal Skullcrobat Joker',
  '조커': 'Performapal Skullcrobat Joker',
  'EM 펜듈럼 매지션': 'Performapal Pendulum Sorcerer',
  '펜듈럼 매지션': 'Performapal Pendulum Sorcerer',
  'EM 오드아이즈 싱크론': 'Performapal Odd-Eyes Synchron',
  'EM 오드아이즈 디졸버': 'Performapal Odd-Eyes Dissolver',
  '디졸버': 'Performapal Odd-Eyes Dissolver',
  'EM 희대의 듀얼리스트': 'Performapal Gentrudo',
  '희대의 듀얼리스트': 'Performapal Gentrudo',
  '룡검사 라스터P': 'Luster Pendulum, the Dracoslayer',
  '라스터P': 'Luster Pendulum, the Dracoslayer',
  
  // 펜듈럼 마법/함정 및 보조 카드
  '성운의 펜듈럼그래프': 'Star Pendulumgraph',
  '성운': 'Star Pendulumgraph',
  '시공의 펜듈럼그래프': 'Time Pendulumgraph',
  '시공': 'Time Pendulumgraph',
  '듀얼리스트 얼라이언스': 'Duelist Alliance',
  '펜듈럼 콜': 'Pendulum Call',
  '펜콜': 'Pendulum Call',
  '펜듈럼 에볼루션': 'Pendulum Evolution',
  '펜에보': 'Pendulum Evolution',

  // 패왕 및 용사 테마 관련
  '패왕문 제로': 'Supreme King Gate Zero',
  '패왕문 인피니티': 'Supreme King Gate Infinity',
  '패왕권룡 다크브룸': 'Supreme King Dragon Darkwurm',
  '다크브룸': 'Supreme King Dragon Darkwurm',
  '패왕권룡 라이트브룸': 'Supreme King Dragon Lightwurm',
  '라이트브룸': 'Supreme King Dragon Lightwurm',
  '패왕신룡 오드아이즈 레볼루션 드래곤': 'Odd-Eyes Revolution Dragon',
  '레볼루션 드래곤': 'Odd-Eyes Revolution Dragon',

  // 엑스트라 덱 (싱크로, 엑시즈, 링크)
  '별을 새기는 마술사': 'Timestar Magician',
  '별새김의 마술사': 'Timestar Magician',
  '별새김': 'Timestar Magician',
  '폭룡검사 이그니스터P': 'Ignister Prominence, the Blasting Dracoslayer',
  '이그니스터P': 'Ignister Prominence, the Blasting Dracoslayer',
  '궤적의 마술사': 'Beyond the Pendulum',
  '비욘드 더 펜듈럼': 'Beyond the Pendulum',
  '비욘펜': 'Beyond the Pendulum',
  '도이의 마술사': 'Exceed the Pendulum',
  '엑시즈 더 펜듈럼': 'Exceed the Pendulum',
  '엑펜': 'Exceed the Pendulum',
  '헤비메탈포제 엘렉트룸': 'Heavymetalfoes Electrumite',
  '헤비메탈포제 엘렉트럼': 'Heavymetalfoes Electrumite',
  '엘렉트룸': 'Heavymetalfoes Electrumite',
  '엘렉트럼': 'Heavymetalfoes Electrumite',
  '신성마황후 셀레네': 'Selene, Queen of the Master Magicians',
  '셀레네': 'Selene, Queen of the Master Magicians',
  '패왕권룡 스타브 베놈': 'Supreme King Dragon Starving Venom',
  '스타브 베놈': 'Supreme King Dragon Starving Venom',
  '패왕권룡 다크 리벨리온': 'Supreme King Dragon Dark Rebellion',
  '다크 리벨리온': 'Supreme King Dragon Dark Rebellion',
  '소명의 신궁-아폴로우사': 'Apollousa, Bow of the Goddess',
  '아폴로우사': 'Apollousa, Bow of the Goddess',
  '액세스코드 토커': 'Accesscode Talker',
  '액세스코드': 'Accesscode Talker',
  '아이피 마스카레나': 'I:P Masquerena',
  '마스카레나': 'I:P Masquerena',
  '구희': 'Promethean Princess, Bestower of Flames',
  '화염의 구희': 'Promethean Princess, Bestower of Flames',
  '양륙의 군함수': 'Amphibious Swarmship Amblowhale',
  '암블로엘': 'Amphibious Swarmship Amblowhale',
  '에스:피 리틀나이트': 'S:P Little Knight',
  '리틀나이트': 'S:P Little Knight',
  '크로노다이버 리도우': 'Chronodiver Redoer',
  '리도우': 'Chronodiver Redoer',
  '심연의 숨은 자': 'Abyss Dweller',
  '심연의 숨은자': 'Abyss Dweller',
  '네가로기어 아제우스': 'Divine Arsenal AA-ZEUS - Sky Thunder',
  '아제우스': 'Divine Arsenal AA-ZEUS - Sky Thunder',
  '바렐로드 S 드래곤': 'Borreload Savage Dragon',
  '바렐로드 새비지 드래곤': 'Borreload Savage Dragon',
  '새비지': 'Borreload Savage Dragon',
  '플뢰르 드 바로네스': 'Baronne de Fleur',
  '바로네스': 'Baronne de Fleur',
  '오드아이즈 보텍스 드래곤': 'Odd-Eyes Vortex Dragon',
  '보텍스': 'Odd-Eyes Vortex Dragon',
  '오드아이즈 앱솔루트 드래곤': 'Odd-Eyes Absolute Dragon',
  '앱솔루트': 'Odd-Eyes Absolute Dragon',
  '오드아이즈 싱크론': 'Odd-Eyes Synchron',

  // 유희왕 필수 범용 패트랩 / 지명자 (Staples)
  '하루 우라라': 'Ash Blossom & Joyous Spring',
  '하루우라라': 'Ash Blossom & Joyous Spring',
  '우라라': 'Ash Blossom & Joyous Spring',
  '증식의 G': 'Maxx "C"',
  '증식의G': 'Maxx "C"',
  '증G': 'Maxx "C"',
  '무한포영': 'Infinite Impermanence',
  '포영': 'Infinite Impermanence',
  '이펙트 뵐러': 'Effect Veiler',
  '뵐러': 'Effect Veiler',
  '무덤의 지명자': 'Called by the Grave',
  '무명자': 'Called by the Grave',
  '말살의 지명자': 'Crossout Designator',
  '말명자': 'Crossout Designator',
  '원시생명체 니비루': 'Nibiru, the Primal Being',
  '니비루': 'Nibiru, the Primal Being',
  '아티팩트 롱기누스': 'Artifact Lancea',
  '롱기누스': 'Artifact Lancea',
  '저택 와라시': 'Ghost Belle & Haunted Mansion',
  '와라시': 'Ghost Belle & Haunted Mansion',
  '드롤 & 로크 버드': 'Droll & Lock Bird',
  '드롤': 'Droll & Lock Bird',
  '삼전의 재': 'Triple Tactics Talent',
  '삼전의 호': 'Triple Tactics Thrust',
  '해피의 깃털': 'Harpie\'s Feather Duster',
  '깃털': 'Harpie\'s Feather Duster',
  '길항승부': 'Evenly Matched',
  '길항': 'Evenly Matched',

  // 단축 약어 매핑
  '천룡': 'Dragonpit Magician',
  '조현': 'Harmonizing Magician',
  '자독': 'Purple Poison Magician',
  '혜안': 'Wisdom-Eye Magician',
  '홍채': 'Double Iris Magician',
  '백익': 'White Wing Magician',
  '흑아': 'Black Fang Magician',
  '아스트로': 'Astrograph Sorcerer',
  '크로노': 'Chronograph Sorcerer'
};
