export const KOREAN_CARD_MAP = {
  // 마술사 핵심 카드
  '천룡의 마술사': 'Dragonpit Magician',
  '조현의 마술사': 'Harmonizing Magician',
  '자독의 마술사': 'Purple Poison Magician',
  '혜안의 마술사': 'Wisdom-Eye Magician',
  '홍채의 마술사': 'Double Iris Magician',
  '백익의 마술사': 'White Wing Magician',
  '흑아의 마술사': 'Black Fang Magician',
  '홍귀의 마술사': 'Oafdragon Magician',
  '용혈의 마술사': 'Dragonpulse Magician',
  '아스트로그래프 마술사': 'Astrograph Sorcerer',
  '크로노그래프 마술사': 'Chronograph Sorcerer',
  '별을 읽는 마술사': 'Stargazer Magician',
  '시간을 읽는 마술사': 'Timegazer Magician',
  '귀룡의 마술사': 'Nobledragon Magician',
  '법안의 마술사': 'Dharma-Eye Magician',
  '조율의 마술사': 'Tuning Magician',
  '블랙 매지션': 'Dark Magician',
  '블랙 매지션 걸': 'Dark Magician Girl',
  '천룡': 'Dragonpit Magician',
  '조현': 'Harmonizing Magician',
  '자독': 'Purple Poison Magician',
  '혜안': 'Wisdom-Eye Magician',
  '홍채': 'Double Iris Magician',
  '아스트로': 'Astrograph Sorcerer',
  '크로노': 'Chronograph Sorcerer',

  // 유희왕 필수 범용 패트랩 / 지명자 (Staples)
  '하루 우라라': 'Ash Blossom & Joyous Spring',
  '하루우라라': 'Ash Blossom & Joyous Spring',
  '우라라': 'Ash Blossom & Joyous Spring',
  '증식의 G': 'Maxx "C"',
  '증식의G': 'Maxx "C"',
  '증G': 'Maxx "C"',
  '무한포영': 'Infinite Impermanence',
  '포영': 'Infinite Impermanence',
  '이펙트 뵐러': 'Effect Veiler',
  '뵐러': 'Effect Veiler',
  '무덤의 지명자': 'Called by the Grave',
  '무명자': 'Called by the Grave',
  '말살의 지명자': 'Crossout Designator',
  '말명자': 'Crossout Designator',
  '원시생명체 니비루': 'Nibiru, the Primal Being',
  '니비루': 'Nibiru, the Primal Being',
  '아티팩트 롱기누스': 'Artifact Lancea',
  '롱기누스': 'Artifact Lancea',
  '저택 와라시': 'Ghost Belle & Haunted Mansion',
  '와라시': 'Ghost Belle & Haunted Mansion',
  '드롤 & 로크 버드': 'Droll & Lock Bird',
  '드롤': 'Droll & Lock Bird',
  '빙검룡 미라제이드': 'Mirrorjade the Iceblade Dragon',
  '미라제이드': 'Mirrorjade the Iceblade Dragon',
  '티아라멘츠 하프니스': 'Tearlaments Havnis',
  '하프니스': 'Tearlaments Havnis',
  '티아라멘츠 허프니스': 'Tearlaments Havnis',
  '허프니스': 'Tearlaments Havnis'
};
